### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by mymedia2** [TelegramMessenger/tgcalls#2]
Thank you very much for video calls in Telegram. Alas, there are no LICENSE statement and copyright notice in the repository. Because of this the code is treated as fully proprietary, and open source projects are forbidden to use this library.

Would you be so kind as to choose some popular license approved by Free Software Foundation: <https://www.gnu.org/licenses/license-list.html>. If copyright holder do this in a clear way by placing all terms of use near the code, it would eliminate most of questions.

**Comment by AndrewLaneX** [comment]
https://github.com/TelegramMessenger/tgcalls/commit/e884535f1854aa57616b162a4901bd60c8287575

**Comment by mymedia2** [comment]
Thank you so much! I appreciate your work!
